static_tf:
  ros__parameters:
    child_frames: 
      - lidar_link
      - imu_link
    parent_frame: base_link

odometry:
  ros__parameters:
    pcl2_topic: /lidar/point_cloud
    base_link: base_link
    use_imu: true
    imu_topic: /imu

map_tf:
  ros__parameters:
    odom_topic: /odom
    scan_match_topic: /scan_match_pose